apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: live-departures-backend
  namespace: argocd
spec:
  destination:
    namespace: live-departures
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: image.repository
        value: ghcr.io/lukasznidecki/live-departures-backend
      - name: name
        value: live-departures-backend
    path: helm/live-departures-backend
    repoURL: git@github.com:lukasznidecki/live-departures-backend.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true